server:
  port: 8081
  servlet:
    context-path: "/fb-management/v1"
management:
  security:
    flag: false
  metrics:
    export:
      statsd:
        flavor: etsy
---
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration,org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration
  application:
    name: @name@
  output:
    ansi:
      enabled: always
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: @db.url@
    username: @db.user@
    password: @db.password@
    hikari:
      idle-timeout: 30000
      maximum-pool-size: 10
    flyway:
      schemas: af

info:
  version: @project.version@
  stage: dev

kafka:
  bootstrap.servers: "localhost:29092"
  consumer-group:
    wb-list: FraudBusterListenerWbList
  topic:
    wblist:
      command: "wb-list-command"
      event.sink: "wb-list-event-sink"
    fraudbusters:
      payment:
        template: "template"
        reference: "template_reference"
        group:
          list: "group"
          reference: "group_reference"
      p2p:
        template: "p2p_template"
        reference: "p2p_reference"
        group:
          list: "p2p_group"
          reference: "p2p_group_reference"
  ssl:
    enable: false
    keystore-location: src/main/resources/cert/kenny-k.struzhkin.p12
    keystore-password: kenny
    key-password: kenny
    server-password: kenny12
    server-keystore-location: src/main/resources/cert/truststore.p12
service:
  p2p:
    url: http://fraudbusters:8022/fraud_p2p/v1
    networkTimeout: 5000
  payment:
    url: http://fraudbusters:8022/fraud_payment/v1
    networkTimeout: 5000
ch.notificator.url: "http://clickhouse-notificator:8080/ch-manager"

keycloak:
  auth-server-url: http://localhost:8080/auth
  realm: SpringBootKeycloack
  resource: login-app
  bearer-only: true
  ssl-required: external
  public-client: true
  enabled: false
