server:
  port: @server.port@
  servlet:
    context-path: "/fb-management/v1"
management:
  security:
    enabled: false
  server:
    port: @management.port@
  metrics:
    export:
      statsd:
        flavor: etsy
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration,org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration
  application:
    name: @name@
  output:
    ansi:
      enabled: always
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: @db.url@
    username: @db.user@
    password: @db.password@
    hikari:
      idle-timeout: 30000
      maximum-pool-size: 10
    flyway:
      schemas: af

info:
  version: @project.version@
  stage: dev

kafka:
  bootstrap-servers: "localhost:29092"
  consumer-group:
    wb-list: FraudBusterListenerWbList
  topic:
    wblist:
      command: "wb-list-command"
      event.sink: "wb-list-event-sink"
    fraudbusters:
      payment:
        template: "template"
        reference: "template_reference"
        group:
          list: "group"
          reference: "group_reference"
      p2p:
        template: "p2p_template"
        reference: "p2p_reference"
        group:
          list: "p2p_group"
          reference: "p2p_group_reference"
      unknown-initiating-entity: unknown_initiating_entity
  ssl:
    enable: false
    keystore-location: src/main/resources/cert/kenny-k.struzhkin.p12
    keystore-password: kenny
    key-password: kenny
    server-password: kenny12
    server-keystore-location: src/main/resources/cert/truststore.p12
service:
  p2p:
    url: http://fraudbusters:8022/fraud_p2p/v1
    networkTimeout: 5000
  payment:
    url: http://localhost:8999/fraud_payment/v1
    networkTimeout: 5000
  historical:
    url: http://localhost:8999/historical_data/v1
    networkTimeout: 5000
  cleaner:
    cron: "-"
    fresh-period: 30
  notification:
    url: http://localhost:8999/notification/v1
    networkTimeout: 5000
  notification-channel:
    url: http://localhost:8999/notification-channel/v1
    networkTimeout: 5000
  notification-template:
    url: http://localhost:8999/notification-template/v1
    networkTimeout: 5000

keycloak:
  auth-server-url: http://localhost:8080/auth
  realm: SpringBootKeycloack
  resource: login-app
  bearer-only: true
  ssl-required: external
  public-client: true
  enabled: false
  principal-attribute: preferred_username

cors.allowed-origins: "http://localhost:4200"

spring.servlet.multipart.max-file-size: 10MB
spring.servlet.multipart.max-request-size: 10MB

parameters.listNames: EMAIL,IP,FINGERPRINT,CARD_TOKEN,BIN,PAN
